### ISSUE TITLE
Wiki seems to be down again. Same as before, shows cloudflare good and host down.

### ISSUE THREAD

**Issue by Palden1710** [BiggerSeries/Wiki#5]

**Comment by RogueLogix** [comment]
This is the host that cloudflare is pointed at, there is nothing I can really do besides wait for them to finish their migration.
<https://clients.desivps.com/index.php?rp=/announcements/7/Important-Announcement---data-.html>

TLDR: upstream host of the VPS host I'm using shutdown almost without notice. They are working on getting their servers up at another datacenter, but until then it will be down. ETA Tuesday 9/12 (pacific)

**Comment by Palden1710** [comment]
Ooof, sorry to hear, but thanks for the update!

**Comment by RogueLogix** [comment]
they still haven't gotten the VPS back up, so I swapped to OVH for hosting the forwarding VPS, its back up now.
